//TODO get types from schemas generated by openapi-ts
import { Schema } from '@src/types/models/api/utils';
import { components } from '@src/types/models/openapi/TransactionsResource';

export type ITransaction = Schema<components, 'SingleTransaction'>;
