//TODO get types from schemas generated by openapi-ts
type PaymentMethodType = 'klarna';

export type ITransaction = {
    id: string;
    amount: {
        currency: 'USD' | 'EUR';
        value: number;
    };
    paymentMethod: {
        type: PaymentMethodType | string;
        lastFourDigits?: number;
    };
    creationDate: string;
    category?: 'ATM';
    status: 'Booked' | 'Pending' | 'Rejected';
    type: 'ATM' | 'Capital' | 'Correction' | 'Fee' | 'Payment' | 'Refund' | 'Chargeback' | 'Transfer' | 'Other';
};
