/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/payouts/{payoutId}": {
    /**
     * Get payout details
     * @description Given a payout ID, it retrieves its details
     */
    get: operations["getPayout"];
  };
  "/v1/payouts": {
    /**
     * Get payouts
     * @description Given filters, provides list of payouts for a balance account
     */
    get: operations["getPayouts"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Amount: {
      /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes). */
      currency: string;
      /**
       * Format: int64
       * @description The amount of the transaction, in [minor units](https://docs.adyen.com/development-resources/currency-codes).
       */
      value: number;
    };
    AmountGrouped: {
      amount?: components["schemas"]["Amount"];
      category?: string;
    };
    Payout: {
      accountHolderId?: string;
      balanceAccountId?: string;
      chargesAmount?: components["schemas"]["Amount"];
      /** Format: date-time */
      createdAt?: string;
      grossAmount?: components["schemas"]["Amount"];
      id?: string;
      netAmount?: components["schemas"]["Amount"];
    };
    PayoutResponse: {
      amountBreakdown?: components["schemas"]["AmountGrouped"][];
      payout?: components["schemas"]["Payout"];
    };
    PayoutsResponse: {
      next?: string;
      payouts?: components["schemas"]["Payout"][];
      prev?: string;
    };
    PayoutsRequest: {
      balanceAccountId: string;
      /** Format: date-time */
      createdSince: string;
      /** Format: date-time */
      createdUntil: string;
      cursor?: string;
      /** Format: int32 */
      limit: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get payout details
   * @description Given a payout ID, it retrieves its details
   */
  getPayout: {
    parameters: {
      path: {
        payoutId: string;
      };
    };
    responses: {
      /** @description OK - the request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["PayoutResponse"];
        };
      };
    };
  };
  /**
   * Get payouts
   * @description Given filters, provides list of payouts for a balance account
   */
  getPayouts: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PayoutsRequest"];
      };
    };
    responses: {
      /** @description OK - the request has succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["PayoutsResponse"];
        };
      };
    };
  };
}
