export {
    DEFAULT_PAYMENT_LINK_STATUS_GROUP,
    EARLIEST_PAYMENT_LINK_DATE_DAYS,
    PAYMENT_LINK_STATUS_GROUPS,
    PAYMENT_LINK_STATUS_GROUPS_FILTER_MAPPING,
    PAYMENT_LINK_STATUS_GROUPS_TABS,
    PAYMENT_LINK_STATUSES,
    PAYMENT_LINK_TYPES,
    PAYMENT_LINKS_TABLE_FIELDS,
} from '../../../domain/src';

export const DEFAULT_PAGE_LIMIT = 10;
export const LIMIT_OPTIONS = [10, 20];
