/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/cashout/configuration': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cashout configuration
         * @description Retrieves the cashout configuration for a given account, including balance, availability, and limits.
         */
        get: operations['getCashoutConfiguration'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/cashout/balanceAccounts': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cashout balance accounts
         * @description Retrieves the list of balance accounts eligible for cashout.
         */
        get: operations['getCashoutBalanceAccounts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/cashout/fees': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cashout fees
         * @description Calculates and returns the fee breakdown for a given cashout amount and currency.
         */
        get: operations['getCashoutFees'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/cashout/transferInstruments': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cashout transfer instruments
         * @description Retrieves the list of transfer instruments available for cashout.
         */
        get: operations['getCashoutTransferInstruments'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/cashout': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cashout history
         * @description Retrieves the list of past cashout transactions for a given account.
         */
        get: operations['getCashoutHistory'];
        put?: never;
        /**
         * Submit cashout
         * @description Submits a cashout request for a given account, amount, and transfer instrument.
         */
        post: operations['submitCashout'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        Amount: {
            /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes). */
            currency: string;
            /**
             * Format: int64
             * @description The amount of the transaction, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
             */
            value: number;
        };
        /** @description Cashout configuration for the account holder. */
        CashoutConfigurationDTO: {
            /** @description The total balance amount of the account. */
            balanceAmount: components['schemas']['Amount'];
            /** @description The amount available for cashout. */
            availableForCashoutAmount: components['schemas']['Amount'];
            /** @description The pending amount not yet settled. */
            pendingAmount: components['schemas']['Amount'];
            /** @description Whether cashout is currently available for this account. */
            isCashoutAvailable: boolean;
            /** @description List of reasons why cashout is unavailable. Empty if cashout is available. */
            unsupportedReasons: string[];
            /**
             * Format: int64
             * @description The minimum cashout amount in minor units.
             */
            minAmount: number;
            /**
             * Format: int64
             * @description The maximum cashout amount in minor units.
             */
            maxAmount: number;
            /** @description The account key identifying the account holder. */
            accountKey: string;
        };
        /** @description A balance account eligible for cashout. */
        CashoutBalanceAccountDTO: {
            /** @description The unique identifier of the balance account. */
            balanceAccountId: string;
            /** @description A human-readable description of the balance account. */
            balanceAccountDescription: string;
        };
        /** @description List of balance accounts eligible for cashout. */
        CashoutBalanceAccountsResponseDTO: {
            data: components['schemas']['CashoutBalanceAccountDTO'][];
        };
        /** @description Fee breakdown for a cashout request. */
        CashoutFeesResponseDTO: {
            /** @description The total cashout amount requested. */
            totalAmount: components['schemas']['Amount'];
            /** @description The fees deducted from the cashout amount. */
            feesAmount: components['schemas']['Amount'];
            /** @description The net amount that will be received after fees. */
            amountToReceive: components['schemas']['Amount'];
            /** @description Detailed breakdown of the fees applied. */
            feeBreakdown: components['schemas']['CashoutFeeBreakdownItemDTO'][];
        };
        /** @description An individual fee line item in the fee breakdown. */
        CashoutFeeBreakdownItemDTO: {
            /** @description The type or description of the fee. */
            type?: string;
            /** @description The fee amount. */
            amount?: components['schemas']['Amount'];
        };
        /** @description A transfer instrument available for cashout. */
        CashoutTransferInstrumentDTO: {
            /** @description The unique identifier of the transfer instrument. */
            transferInstrumentId: string;
            /** @description The type of the transfer instrument (e.g. 'visa', 'bank'). */
            type: string;
            /** @description A masked description of the transfer instrument. */
            description: string;
        };
        /** @description List of transfer instruments available for cashout. */
        CashoutTransferInstrumentsResponseDTO: {
            data: components['schemas']['CashoutTransferInstrumentDTO'][];
        };
        /** @description Request body for submitting a cashout. */
        CashoutSubmitRequestDTO: {
            /** @description The account key identifying the account holder. */
            accountKey: string;
            /** @description The cashout amount. */
            amount: components['schemas']['Amount'];
            /** @description The ID of the transfer instrument to receive the cashout. */
            transferInstrumentId: string;
        };
        /** @description Response after a successful cashout submission. */
        CashoutSubmitResponseDTO: {
            /** @description The status of the cashout submission. */
            status: string;
        };
        /** @description A historical cashout transaction. */
        CashoutHistoryItemDTO: {
            /** @description The balance account code associated with the cashout. */
            balanceAccountCode: string;
            /** @description The cashout amount. */
            amount: components['schemas']['Amount'];
            /** @description The fee amount charged for the cashout. */
            feeAmount: components['schemas']['Amount'];
            /** @description The transfer instrument used for the cashout. */
            transferInstrument: components['schemas']['CashoutTransferInstrumentDTO'];
            /** @description A unique reference for the cashout transaction. */
            reference: string;
            /** @description A description of the cashout transaction. */
            descriptionReference: string;
            /**
             * Format: date-time
             * @description The date and time the cashout was created.
             */
            creationDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
    /**
     * Get cashout configuration
     * @description Retrieves the cashout configuration for a given account, including balance, availability, and limits.
     */
    getCashoutConfiguration: {
        parameters: {
            query: {
                /** @description The account key identifying the account holder. */
                accountKey: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashoutConfigurationDTO'];
                };
            };
        };
    };
    /**
     * Get cashout balance accounts
     * @description Retrieves the list of balance accounts eligible for cashout.
     */
    getCashoutBalanceAccounts: {
        parameters: {
            query: {
                /** @description The account key identifying the account holder. */
                accountKey: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashoutBalanceAccountsResponseDTO'];
                };
            };
        };
    };
    /**
     * Get cashout fees
     * @description Calculates and returns the fee breakdown for a given cashout amount and currency.
     */
    getCashoutFees: {
        parameters: {
            query: {
                /** @description The account key identifying the account holder. */
                accountKey: string;
                /**
                 * Format: int64
                 * @description The cashout amount in minor units.
                 */
                amount: number;
                /** @description The three-character ISO currency code. */
                currency: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashoutFeesResponseDTO'];
                };
            };
        };
    };
    /**
     * Get cashout transfer instruments
     * @description Retrieves the list of transfer instruments available for cashout.
     */
    getCashoutTransferInstruments: {
        parameters: {
            query: {
                /** @description The account key identifying the account holder. */
                accountKey: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashoutTransferInstrumentsResponseDTO'];
                };
            };
        };
    };
    /**
     * Submit cashout
     * @description Submits a cashout request for a given account, amount, and transfer instrument.
     */
    submitCashout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CashoutSubmitRequestDTO'];
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashoutSubmitResponseDTO'];
                };
            };
        };
    };
    /**
     * Get cashout history
     * @description Retrieves the list of past cashout transactions for a given account.
     */
    getCashoutHistory: {
        parameters: {
            query: {
                /** @description The account key identifying the account holder. */
                accountKey: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashoutHistoryItemDTO'][];
                };
            };
        };
    };
}
