/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    'v1/countries': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Countries
         * @description List of available countries and regions
         */
        get: operations['getCountries'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
    schemas: {
        Country: {
            countryCode: string;
            countryName?: string;
        };
    };
}
export type $defs = Record<string, never>;
export interface operations {
    getCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        data?: components['schemas']['Country'][];
                    };
                    'application/xml': Record<string, never>;
                };
            };
        };
    };
}
