/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/disputes': {
        /**
         * Get reports
         * @description Given filters, provides list of reports for a balance account
         */
        get: operations['getDisputes'];
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        Dispute: {
            id: string;
            status: 'action_needed' | 'won' | 'lost' | 'docs_submitted' | 'under_review';
            createdAt: string;
            dueDate?: string;
            paymentMethod: {
                /** @description Last four digits of the card */
                lastFourDigits?: string;
                /** @description Payment method type code of the transaction f.e. klarna, visa, mc */
                type: string;

                description?: string;
            };
            bankAccount: {
                /** @description Last four digits of the account number or IBAN. */
                accountNumberLastFourDigits: string;
            };
            reasonCode: string;
            amount: {
                currency: string;
                value: number;
            };
        };
        Link: {
            /** @description Cursor for a different page */
            cursor: string;
        };
        Links: {
            /** @description Link to a different page */
            next: components['schemas']['Link'];
            /** @description Link to a different page */
            prev: components['schemas']['Link'];
        };
        DisputesListResponseDTO: {
            _links?: components['schemas']['Links'];
            data: components['schemas']['Dispute'][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
    /**
     * Get reports
     * @description Given filters, provides list of reports for a balance account
     */
    getDisputes: {
        parameters: {
            query: {
                statusGroup?: 'closed' | 'open';
                balanceAccountId?: string;
                createdSince?: string;
                createdUntil?: string;
                reasonCode?: string;
                limit?: number;
                cursor?: string;
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                content: {
                    'application/json': components['schemas']['DisputesListResponseDTO'];
                };
            };
        };
    };
    getDispute: {
        parameters: {
            path: {
                disputeId: string;
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                content: {
                    'application/json': components['schemas']['Dispute'];
                };
            };
        };
    };
}
