/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/paybylink/paymentLinks/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add @Operation annotation to provide a description */
        post: operations["createPBLPaymentLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paybylink/paymentLinks/{storeId}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations["getPayByLinkConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paybylink/settings/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations["getPayByLinkSettings"];
        put?: never;
        /** @description Add @Operation annotation to provide a description */
        post: operations["savePayByLinkSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paybylink/themes/{storeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations["getPayByLinkTheme"];
        put?: never;
        /** @description Add @Operation annotation to provide a description */
        post: operations["updatePayByLinkTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paybylink/paymentLinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations["getPaymentLinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paybylink/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations["payByLinkFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePaymentLinkResponse: {
            paymentLinkId?: string;
            status?: string;
            /** Format: date-time */
            updatedAt?: string;
            url?: string;
        };
        Address: {
            city?: string;
            country?: string;
            houseNumberOrName?: string;
            postalCode?: string;
            street?: string;
        };
        Amount: {
            /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes) of the amount. */
            currency: string;
            /**
             * Format: int64
             * @description The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
             */
            value: number;
        };
        CreatePaymentLinkRequestDTO: {
            amount: components["schemas"]["Amount"];
            billingAddress?: components["schemas"]["Address"];
            countryCode: string;
            /** Format: date-time */
            deliverAt?: string;
            deliveryAddress?: components["schemas"]["Address"];
            description?: string;
            linkType?: components["schemas"]["PaymentLinkType"];
            linkValidity: components["schemas"]["CreatePaymentLinkValidity"];
            reference: string;
            sendLinkToShopper?: boolean;
            sendSuccessEmailToShopper?: boolean;
            /** Format: email */
            shopperEmail?: string;
            shopperLocale?: string;
            shopperName?: components["schemas"]["ShopperName"];
            shopperReference?: string;
            telephoneNumber?: string;
        };
        CreatePaymentLinkValidity: {
            durationUnit: components["schemas"]["DurationUnit"];
            /** Format: int32 */
            quantity: number;
        };
        /** @enum {string} */
        DurationUnit: "minute" | "hour" | "day" | "week";
        /** @enum {string} */
        PaymentLinkType: "open" | "singleUse";
        ShopperName: {
            firstName?: string;
            lastName?: string;
        };
        ConfigurationResponse: {
            amountValue: components["schemas"]["FieldRequirementVoid"];
            billingAddress?: components["schemas"]["FieldRequirementVoid"];
            countryCode: components["schemas"]["FieldRequirementString"];
            currency: components["schemas"]["FieldRequirementString"];
            deliveryAddress?: components["schemas"]["FieldRequirementVoid"];
            deliveryDate?: components["schemas"]["FieldRequirementVoid"];
            description?: components["schemas"]["FieldRequirementVoid"];
            emailAddress?: components["schemas"]["FieldRequirementVoid"];
            linkType?: components["schemas"]["FieldRequirementLinkType"];
            linkValidity?: components["schemas"]["FieldRequirementLinkValidity"];
            merchantReference?: components["schemas"]["FieldRequirementVoid"];
            phoneNumber?: components["schemas"]["FieldRequirementVoid"];
            sendLinkToShopper?: components["schemas"]["FieldRequirementVoid"];
            sendSuccessEmailToShopper?: components["schemas"]["FieldRequirementVoid"];
            shopperLocale: components["schemas"]["FieldRequirementString"];
            shopperName?: components["schemas"]["FieldRequirementVoid"];
            shopperReference: components["schemas"]["FieldRequirementVoid"];
        };
        FieldRequirementLinkType: {
            options?: components["schemas"]["LinkType"][];
            required: boolean;
        };
        FieldRequirementLinkValidity: {
            options?: components["schemas"]["LinkValidity"][];
            required: boolean;
        };
        FieldRequirementString: {
            options?: string[];
            required: boolean;
        };
        FieldRequirementVoid: {
            options?: Record<string, never>[];
            required: boolean;
        };
        /** @enum {string} */
        LinkType: "singleUse" | "open";
        StatusGroup: 'active' | 'inactive';
        /** @enum {string} */
        SortDirection: 'asc' | 'desc';
        LinkValidity: {
            durationUnit: components["schemas"]["DurationUnit"];
            /** Format: int32 */
            quantity: number;
            type: components["schemas"]["Type"];
        };
        /** @enum {string} */
        Type: "fixed" | "flexible";
        PayByLinkSettingsResponse: {
            /** @description Terms of service url */
            termsOfServiceUrl: string;
        };
        ThemeDTO: {
            brandName?: string;
            fullWidthLogoUrl?: string;
            logoUrl?: string;
        };
        Link: {
            /** @description Cursor for a different page */
            cursor: string;
        };
        Links: {
            /** @description Link to a different page */
            next?: components["schemas"]["Link"];
            /** @description Link to a different page */
            prev?: components["schemas"]["Link"];
        };
        /** @enum {string} */
        PaymentLinkStatus: "active" | "paymentPending" | "expired" | "completed";
        PaymentLinksItem: {
            /** @description Amount */
            amount: components["schemas"]["Amount"];
            /**
             * Format: date-time
             * @description Creation Date
             */
            creationDate: string;
            /**
             * Format: date-time
             * @description Expiration Date
             */
            expirationDate: string;
            /** @description Payment Link Type */
            linkType: components["schemas"]["PaymentLinkType"];
            /** @description Merchant Reference */
            merchantReference: string;
            /** @description Payment Link ID */
            paymentLinkId: string;
            /** @description Shopper Email */
            shopperEmail?: string;
            /** @description Status */
            status: components["schemas"]["PaymentLinkStatus"];
            /** @description Store Code */
            storeCode?: string;
        };
        PaymentLinksResponse: {
            /** @description Links */
            _links: components["schemas"]["Links"];
            /** @description Payment links made within the filters provided */
            data: components["schemas"]["PaymentLinksItem"][];
        };
        FiltersResponseDTO: {
            linkTypes: components["schemas"]["PayByLinkLinkType"][];
            statuses: components["schemas"]["PaymentLinkStatuses"];
        };
        /** @enum {string} */
        PayByLinkLinkType: "singleUse" | "open";
        /** @enum {string} */
        PayByLinkStatus: "completed" | "expired" | "active" | "paymentPending";
        PaymentLinkStatuses: {
            active?: components["schemas"]["PayByLinkStatus"][];
            inactive?: components["schemas"]["PayByLinkStatus"][];
        };
        SavePayByLinkSettingsRequest: {
            termsOfServiceUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPBLPaymentLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreatePaymentLinkRequestDTO"];
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePaymentLinkResponse"];
                };
            };
        };
    };
    getPayByLinkConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationResponse"];
                };
            };
        };
    };
    getPayByLinkSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayByLinkSettingsResponse"];
                };
            };
        };
    };
    savePayByLinkSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SavePayByLinkSettingsRequest"];
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayByLinkSettingsResponse"];
                };
            };
        };
    };
    getPayByLinkTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDTO"];
                };
            };
        };
    };
    updatePayByLinkTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    brandName: string;
                };
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDTO"];
                };
            };
        };
    };
    getPaymentLinks: {
        parameters: {
            query?: {
                paymentLinkId?: string;
                cursor?: string;
                limit?: number;
                createdSince?: string;
                createdUntil?: string;
                statuses?: string[];
                statusGroup?: string;
                currency?: string;
                amount?: number;
                linkTypes?: string[];
                storeIds?: string[];
                merchantReference?: string;
                sortDirection?: components['schemas']['SortDirection'];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentLinksResponse"];
                };
            };
        };
    };
    payByLinkFilters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponseDTO"];
                };
            };
        };
    };
}
