/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/paymentInstruments/{paymentInstrumentId}/networkTokenActivationData': {
        /** @description Add @Operation annotation to provide a description */
        get: operations['getNetworkTokenActivationData'];
        /** @description Add @Operation annotation to provide a description */
        post: operations['createNetworkTokenActivationData'];
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        NetworkTokenActivationDataResponse: {
            sdkInput?: string;
        };
        NetworkTokenActivationDataRequest: {
            sdkOutput?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
    /** @description Add @Operation annotation to provide a description */
    getNetworkTokenActivationData: {
        parameters: {
            path: {
                paymentInstrumentId: string;
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                content: {
                    'application/json': components['schemas']['NetworkTokenActivationDataResponse'];
                };
            };
        };
    };
    /** @description Add @Operation annotation to provide a description */
    createNetworkTokenActivationData: {
        parameters: {
            path: {
                paymentInstrumentId: string;
            };
        };
        requestBody?: {
            content: {
                'application/json': components['schemas']['NetworkTokenActivationDataRequest'];
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                content: {
                    'application/json': components['schemas']['NetworkTokenActivationDataResponse'];
                };
            };
        };
    };
}
