[build]
  edge_functions = "netlify/edge-functions"

[context."chore/level-access-demo"]
    [context."chore/level-access-demo".build]
        command = "npm run build && npm run build:demo"
        publish = ".demo"

[[edge_functions]]
  path = "/api/*"
  function = "proxy-requests"
