sonar.projectKey=Adyen_adyen-platform-experience-web
sonar.organization=adyen
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.*,**/*.spec.*
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/declarations/**,**/storybook-static/**,**/*.stories.*,**/__testing__/**,packages/shared/testing/**
sonar.coverage.exclusions=**/*.test.*,**/*.spec.*,**/*.stories.*,**/__testing__/**,**/testing/**,**/index.ts,**/index.tsx,**/constants.ts,**/constants.tsx,**/types.ts,**/types.tsx,**/*.d.ts,**/*.config.ts,config/**,endpoints/**,envs/**,mocks/**,netlify/**,scripts/**,tests/**,packages/domains/*/tests/**,packages/shared/assets/**,packages/shared/lib/**,packages/shared/testing/**,packages/shared/types/**,packages/tools/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
