name: Setup Smartling
description: Setup Smartling for translation workflows
runs:
  using: composite
  steps:
    - name: Create the configuration file
      shell: sh
      run: |
        cat <<EOF >> .smartlingrc
        SMARTLING_PROJECT_ID=${{ secrets.SMARTLING_PROJECT }}
        SMARTLING_USER_IDENTIFIER=${{ secrets.SMARTLING_USER_IDENTIFIER }}
        SMARTLING_USER_SECRET=${{ secrets.SMARTLING_USER_SECRET }}
        EOF
