/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/capital/capitalStates': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capital State
         * @description Returns the capital state with active grants and offers
         */
        get: operations['getCapitalState'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Amount: {
            /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes) of the amount. */
            currency: string;
            /**
             * Format: int64
             * @description The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
             */
            value: number;
        };
        /** @enum {string} */
        CapitalState: 'NOT_ELIGIBLE' | 'OFFER_ELIGIBLE' | 'REQUESTED_OR_ACTIVE_GRANT' | 'EARLY_RENEWAL_ELIGIBLE';
        CapitalStateDTO: {
            activeOrRequestedGrants: components['schemas']['GrantResponseDTO'][];
            capitalState: components['schemas']['CapitalState'];
            dynamicOffer?: components['schemas']['DynamicOffersResponseDTO'];
        };
        DynamicOffersResponseDTO: {
            maxAmount: components['schemas']['Amount'];
            minAmount: components['schemas']['Amount'];
            /** Format: int32 */
            step: number;
        };
        FundsCollectionDetailDTO: {
            beneficiaryName: string;
            order: string[];
            region: string;
        };
        GBCapitalFundsCollection: Omit<
            WithRequired<components['schemas']['FundsCollectionDetailDTO'], 'beneficiaryName' | 'order' | 'region'>,
            'region'
        > & {
            accountNumber: string;
            iban?: string;
            sortCode: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            region: 'GB';
        };
        GrantResponseDTO: {
            balanceAccountCode: string;
            balanceAccountDescription?: string;
            /** Format: int32 */
            expectedRepaymentPeriodDays: number;
            feesAmount: components['schemas']['Amount'];
            grantAmount: components['schemas']['Amount'];
            id: string;
            /** Format: int32 */
            maximumRepaymentPeriodDays?: number;
            missingActions?: components['schemas']['MissingActionDTO'][];
            /** Format: date-time */
            offerExpiresAt?: string;
            remainingFeesAmount: components['schemas']['Amount'];
            remainingGrantAmount: components['schemas']['Amount'];
            remainingTotalAmount: components['schemas']['Amount'];
            renewal?: components['schemas']['RenewalDTO'];
            repaidFeesAmount: components['schemas']['Amount'];
            repaidGrantAmount: components['schemas']['Amount'];
            repaidTotalAmount: components['schemas']['Amount'];
            /** Format: int64 */
            repaymentPeriodLeft: number;
            /** Format: int32 */
            repaymentRate: number;
            revocationAccount?: components['schemas']['FundsCollectionDetailDTO'];
            status: components['schemas']['GrantStatus'];
            /** Format: date-time */
            termEndsAt: string;
            thresholdAmount: components['schemas']['Amount'];
            totalAmount: components['schemas']['Amount'];
            transferInstruments?: components['schemas']['TransferInstrumentReference'][];
            unscheduledRepaymentAccounts?: components['schemas']['FundsCollectionDetailDTO'][];
        };
        /** @enum {string} */
        GrantStatus: 'Pending' | 'Active' | 'Repaid' | 'Failed' | 'WrittenOff' | 'Revoked';
        MissingActionDTO: {
            type: components['schemas']['MissingActionType'];
        };
        /** @enum {string} */
        MissingActionType: 'signToS' | 'AnaCredit';
        NLCapitalFundsCollection: Omit<
            WithRequired<components['schemas']['FundsCollectionDetailDTO'], 'beneficiaryName' | 'order' | 'region'>,
            'region'
        > & {
            iban: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            region: 'NL';
        };
        RenewalDTO: {
            available: boolean;
            minimumRenewalAmount: components['schemas']['Amount'];
            /** Format: int32 */
            targetRepaymentPercentage: number;
        };
        TransferInstrumentReference: {
            /** @description The masked IBAN or bank account number. */
            accountIdentifier: string;
        };
        USCapitalFundsCollection: Omit<
            WithRequired<components['schemas']['FundsCollectionDetailDTO'], 'beneficiaryName' | 'order' | 'region'>,
            'region'
        > & {
            accountNumber: string;
            routingNumber: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            region: 'US';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCapitalState: {
        parameters: {
            query: {
                accountHolderId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CapitalStateDTO'];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
