export const ACCORDION_BASE_CLASS = 'adyen-pe-accordion';
export const ACCORDION_HEADER_CLASS = ACCORDION_BASE_CLASS + '__header';
export const ACCORDION_HEADER_CONTAINER_CLASS = ACCORDION_HEADER_CLASS + '-container';
export const ACCORDION_HEADER_CONTROLLER_CLASS = ACCORDION_HEADER_CLASS + '-controller';
export const ACCORDION_CONTENT_CLASS = ACCORDION_HEADER_CLASS + '__content';
