/**
 * Type declarations for virtual:tree-shaken-icons module.
 *
 * The virtual module is generated at build time and tree-shakes to only
 * include icons actually used in the code. TypeScript sees all possible
 * icon names for autocomplete, while the runtime bundle only includes what's used.
 *
 * This file is auto-generated by scripts/generate-icon-types.ts
 * Run: pnpm run types:generate:icons
 */

declare module 'virtual:tree-shaken-icons' {
    /**
     * Union type of all available icon names.
     * Auto-discovered from src/images/icons/*.svg
     *
     * Total icons: 30
     */
    export type IconName =
        | 'angle-right'
        | 'arrow-right'
        | 'checkbox-disabled'
        | 'checkmark'
        | 'checkmark-circle-fill'
        | 'checkmark-square-fill'
        | 'chevron-down'
        | 'chevron-left'
        | 'chevron-right'
        | 'chevron-up'
        | 'chevron-up-down'
        | 'cog'
        | 'copy'
        | 'cross'
        | 'cross-circle-fill'
        | 'download'
        | 'external-link'
        | 'filter'
        | 'info'
        | 'info-filled'
        | 'minus-circle-outline'
        | 'plus'
        | 'plus-circle-outline'
        | 'search'
        | 'square'
        | 'square-small-fill'
        | 'trash-can'
        | 'upload'
        | 'warning'
        | 'warning-filled';

    /**
     * Icon registry mapping icon names to their dynamic import functions.
     * Tree-shaken at build time to only include icons actually used in the code.
     */
    export const icons: Record<IconName, () => Promise<{ default: any }>>;
}
