/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/insights/{accountCode}/charts/revenue': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations['getRevenue'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/insights/{accountCode}/charts/sales': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations['getSales'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/insights/{accountCode}/charts/transactionTypes': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Add @Operation annotation to provide a description */
        get: operations['getTransactionTypes'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Amount: {
            /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes) of the amount. */
            currency: string;
            /**
             * Format: int64
             * @description The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
             */
            value: number;
        };
        /**
         * @description A general representation of a chart. This is general enough to be used to represent timeseries line charts,
         *     bar charts etc. A chart consists of xValues shared across one or more series. The series values are all of the
         *     same type. The separation of x and y is done to prevent response bloat (i.e. repetition of xValues).
         */
        ChartComparisonAxisLabelValueWithChange: {
            /** @description One or more series associated with the xValues */
            series: components['schemas']['SeriesValueWithChange'][];
            /**
             * @description Depending on the chart type, the xValue may consist of categorical (for example labels in a barchart)
             *     or continuous (for example datetime values in timeseries charts) labels.
             */
            xValues: components['schemas']['ComparisonAxisLabel'][];
        };
        /**
         * @description A general representation of a chart. This is general enough to be used to represent timeseries line charts,
         *     bar charts etc. A chart consists of xValues shared across one or more series. The series values are all of the
         *     same type. The separation of x and y is done to prevent response bloat (i.e. repetition of xValues).
         */
        ChartOffsetDateTimeAmount: {
            /** @description One or more series associated with the xValues */
            series: components['schemas']['SeriesAmount'][];
            /**
             * @description Depending on the chart type, the xValue may consist of categorical (for example labels in a barchart)
             *     or continuous (for example datetime values in timeseries charts) labels.
             */
            xValues: string[];
        };
        /**
         * @description A general representation of a chart. This is general enough to be used to represent timeseries line charts,
         *     bar charts etc. A chart consists of xValues shared across one or more series. The series values are all of the
         *     same type. The separation of x and y is done to prevent response bloat (i.e. repetition of xValues).
         */
        ChartOffsetDateTimeLong: {
            /** @description One or more series associated with the xValues */
            series: components['schemas']['SeriesLong'][];
            /**
             * @description Depending on the chart type, the xValue may consist of categorical (for example labels in a barchart)
             *     or continuous (for example datetime values in timeseries charts) labels.
             */
            xValues: string[];
        };
        /**
         * @description When comparing two periods (for example year-on-year), the points on the x-axis may refer to a date in the
         *     current period, or a date in the previous period. It is up to the frontend to decide how to visualise this.
         */
        ComparisonAxisLabel: {
            /** Format: date-time */
            current: string;
            /** Format: date-time */
            previous: string;
        };
        /** @description A series consists of a label and list of values. */
        SeriesAmount: {
            /**
             * @description The number of values in a series will always equal the number of xValues. A datapoint may be null,
             *     for example to distinguish between data being unavailable and a 0 value.
             */
            data: components['schemas']['Amount'][];
            /** @description Name of the series */
            name: components['schemas']['SeriesLabel'];
        };
        /** @enum {string} */
        SeriesLabel: 'refund' | 'dispute' | 'fee' | 'comparison' | 'totalVolume' | 'totalRevenue' | 'netRevenue' | 'currentPeriod' | 'previousPeriod';
        /** @description A series consists of a label and list of values. */
        SeriesLong: {
            /**
             * @description The number of values in a series will always equal the number of xValues. A datapoint may be null,
             *     for example to distinguish between data being unavailable and a 0 value.
             */
            data: number[];
            /** @description Name of the series */
            name: components['schemas']['SeriesLabel'];
        };
        /** @description A series consists of a label and list of values. */
        SeriesValueWithChange: {
            /**
             * @description The number of values in a series will always equal the number of xValues. A datapoint may be null,
             *     for example to distinguish between data being unavailable and a 0 value.
             */
            data: components['schemas']['ValueWithChange'][];
            /** @description Name of the series */
            name: components['schemas']['SeriesLabel'];
        };
        /** @description A value in combination with a ratio indicating how much the value has changed. */
        ValueWithChange: {
            /**
             * Format: double
             * @description A ratio indicating change, may be null if change is not representable. Should be multiplied by 100 to obtain the percentage change
             */
            change?: number;
            /** Format: int64 */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRevenue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChartOffsetDateTimeAmount'];
                };
            };
        };
    };
    getSales: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChartComparisonAxisLabelValueWithChange'];
                };
            };
        };
    };
    getTransactionTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChartOffsetDateTimeLong'];
                };
            };
        };
    };
}
