/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/payouts': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payouts
         * @description Given filters, provides list of payouts for a balance account
         */
        get: operations['getPayouts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/payouts/breakdown': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payout details
         * @description Given a payout ID, it retrieves its details
         */
        get: operations['getPayout'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Amount: {
            /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes) of the amount. */
            currency: string;
            /**
             * Format: int64
             * @description The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
             */
            value: number;
        };
        AmountBreakdowns: {
            adjustmentBreakdown: components['schemas']['AmountGroupedDTO'][];
            fundsCapturedBreakdown: components['schemas']['AmountGroupedDTO'][];
        };
        AmountGroupedDTO: {
            amount: components['schemas']['Amount'];
            category: string;
        };
        Link: {
            /** @description Cursor for a different page */
            cursor: string;
        };
        Links: {
            /** @description Link to a different page */
            next?: components['schemas']['Link'];
            /** @description Link to a different page */
            prev?: components['schemas']['Link'];
        };
        PayoutDTO: {
            /** @description Adjustment amount */
            adjustmentAmount: components['schemas']['Amount'];
            /**
             * Format: date-time
             * @description Date created
             */
            createdAt: string;
            /** @description Funds Captured amount */
            fundsCapturedAmount: components['schemas']['Amount'];
            /** @description Payout amount */
            payoutAmount: components['schemas']['Amount'];
            /** @description Unpaid amount */
            unpaidAmount: components['schemas']['Amount'];
        };
        PayoutResponseDTO: {
            amountBreakdowns: components['schemas']['AmountBreakdowns'];
            payout: components['schemas']['PayoutDTO'];
        };
        PayoutsResponseDTO: {
            /** @description Links */
            _links: components['schemas']['Links'];
            /** @description Payouts made within the filters provided for given balanceAccountId */
            data: components['schemas']['PayoutDTO'][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPayouts: {
        parameters: {
            query: {
                balanceAccountId: string;
                createdSince?: string;
                createdUntil?: string;
                cursor?: string;
                limit?: number;
                minPayoutAmount?: number;
                maxPayoutAmount?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PayoutsResponseDTO'];
                };
            };
        };
    };
    getPayout: {
        parameters: {
            query: {
                balanceAccountId: string;
                createdAt?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PayoutResponseDTO'];
                };
            };
        };
    };
}
