/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/reports': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get reports
         * @description Given filters, provides list of reports for a balance account
         */
        get: operations['getReports'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/reports/download': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download report
         * @description Download a specific report
         */
        get: operations['downloadReport'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standardized error response following RFC-7807 format */
        DefaultErrorResponseEntity: {
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description Unique business error code. */
            errorCode?: string;
            /** @description A URI that identifies the specific occurrence of the problem if applicable. */
            instance?: string;
            /** @description Array of fields with validation errors when applicable. */
            invalidFields?: components['schemas']['InvalidField'][];
            /** @description The unique reference for the request. */
            requestId?: string;
            /**
             * Format: int32
             * @description The HTTP status code.
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. */
            title?: string;
            /** @description A URI that identifies the validation error type. It points to human-readable documentation for the problem type. */
            type?: string;
        };
        GeneratedReport: {
            /** Format: date-time */
            createdAt?: string;
            type?: components['schemas']['ReportType'];
        };
        InvalidField: {
            /** @description Description of the validation error. */
            message: string;
            /** @description The field that has an invalid value. */
            name: string;
            /** @description The invalid value. */
            value: string;
        };
        Link: {
            /** @description Cursor for a different page */
            cursor: string;
        };
        Links: {
            /** @description Link to a different page */
            next?: components['schemas']['Link'];
            /** @description Link to a different page */
            prev?: components['schemas']['Link'];
        };
        /** @enum {string} */
        ReportType: 'payout';
        ReportsListResponseDTO: {
            _links?: components['schemas']['Links'];
            data?: components['schemas']['GeneratedReport'][];
        };
        StreamingOutput: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getReports: {
        parameters: {
            query: {
                balanceAccountId: string;
                type: string;
                createdSince?: string;
                createdUntil?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ReportsListResponseDTO'];
                };
            };
        };
    };
    downloadReport: {
        parameters: {
            query: {
                balanceAccountId: string;
                type: string;
                createdAt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'text/csv': components['schemas']['StreamingOutput'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DefaultErrorResponseEntity'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DefaultErrorResponseEntity'];
                };
            };
        };
    };
}
