/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/transactions': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transactions
         * @description Given filters, provides list of transactions for a balance account
         */
        get: operations['getTransactions'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/transactions/download': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download transactions
         * @description Given filters, provides a CSV file with found transactions
         */
        get: operations['downloadTransactions'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/transactions/totals': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction totals
         * @description Given filters, provides total of incomings and expenses for all transactions matching the criteria
         */
        get: operations['getTransactionTotals'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/transactions/{transactionId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction details
         * @description Given a transaction ID, it retrieves its details
         */
        get: operations['getTransaction'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/transactions/{transactionId}/refundPayment': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add @Operation annotation to provide a description */
        post: operations['initiateRefund'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Amount: {
            /** @description The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes) of the amount. */
            currency: string;
            /**
             * Format: int64
             * @description The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
             */
            value: number;
        };
        BankAccount: {
            /** @description Last four digits of the account number or IBAN. */
            accountNumberLastFourDigits: string;
        };
        /** @enum {string} */
        Category: 'ATM' | 'Capital' | 'Correction' | 'Fee' | 'Payment' | 'Refund' | 'Chargeback' | 'Transfer' | 'Other';
        /** @description Standardized error response following RFC-7807 format */
        DefaultErrorResponseEntity: {
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description Unique business error code. */
            errorCode?: string;
            /** @description A URI that identifies the specific occurrence of the problem if applicable. */
            instance?: string;
            /** @description Array of fields with validation errors when applicable. */
            invalidFields?: components['schemas']['InvalidField'][];
            /** @description The unique reference for the request. */
            requestId?: string;
            /**
             * Format: int32
             * @description The HTTP status code.
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. */
            title?: string;
            /** @description A URI that identifies the validation error type. It points to human-readable documentation for the problem type. */
            type?: string;
        };
        ExistingRefund: {
            amount: components['schemas']['Amount'];
            status: components['schemas']['RefundStatus'];
        };
        InvalidField: {
            /** @description Description of the validation error. */
            message: string;
            /** @description The field that has an invalid value. */
            name: string;
            /** @description The invalid value. */
            value: string;
        };
        Link: {
            /** @description Cursor for a different page */
            cursor: string;
        };
        Links: {
            /** @description Link to a different page */
            next?: components['schemas']['Link'];
            /** @description Link to a different page */
            prev?: components['schemas']['Link'];
        };
        PaymentMethod: {
            /** @description Payment method name, such as PayPal, Mastercard etc. */
            description?: string;
            /** @description Last four digits of the payment method used (e.g. a credit card, a debit card, an IBAN) */
            lastFourDigits?: string;
            /** @description Payment method type code of the transaction, e.g. 'klarna', 'visa', 'mc' */
            type: string;
        };
        RefundDetails: {
            refundLocked?: boolean;
            refundMode: components['schemas']['RefundMode'];
            refundStatuses?: components['schemas']['ExistingRefund'][];
            refundableAmount?: components['schemas']['Amount'];
        };
        /** @enum {string} */
        RefundMode: 'non_refundable' | 'partially_refundable_any_amount' | 'fully_refundable_only';
        /** @enum {string} */
        RefundReason: 'requested_by_customer' | 'issue_with_item_sold' | 'fraudulent' | 'duplicate' | 'other';
        RefundRequest: {
            amount: components['schemas']['Amount'];
            refundReason: components['schemas']['RefundReason'];
        };
        RefundResponse: {
            amount: components['schemas']['Amount'];
            refundReason: string;
            status: string;
        };
        /** @enum {string} */
        RefundStatus: 'in_progress' | 'completed' | 'failed';
        RefundTransactionDetails: {
            originalPaymentId?: string;
            refundPspReference: string;
            refundReason?: components['schemas']['RefundReason'];
            refundType: components['schemas']['RefundType'];
        };
        /** @enum {string} */
        RefundType: 'partial' | 'full';
        SingleTransaction: {
            /** @description Amount */
            amount: components['schemas']['Amount'];
            /** @description BalanceAccount ID */
            balanceAccountId: string;
            /** @description Information about the bank account */
            bankAccount?: components['schemas']['BankAccount'];
            /** @description Category */
            category: components['schemas']['Category'];
            /**
             * Format: date-time
             * @description Date created
             */
            createdAt: string;
            /** @description The remaining amount on the payment without this split */
            deductedAmount: components['schemas']['Amount'];
            /** @description ID */
            id: string;
            /** @description Amount in original PSP payment */
            originalAmount: components['schemas']['Amount'];
            /** @description Payment method or payment instrument */
            paymentMethod?: components['schemas']['PaymentMethod'];
            /** @description When applicable, the PSP reference of the PSP payment */
            paymentPspReference?: string;
            /** @description Additional data related to refund operations */
            refundDetails?: components['schemas']['RefundDetails'];
            /** @description When Category is refund, additional information and references related to the refund */
            refundMetadata?: components['schemas']['RefundTransactionDetails'];
            /** @description Status */
            status: components['schemas']['Status'];
        };
        /** @enum {string} */
        SortDirection: 'asc' | 'desc';
        /** @enum {string} */
        Status: 'Pending' | 'Booked' | 'Reversed' | 'Unknown';
        StreamingOutput: Record<string, never>;
        TransactionTotal: {
            /** @description ISO currency code */
            currency: string;
            /**
             * Format: int64
             * @description Sum of expenses of transactions (negative transaction amount values)
             */
            expenses: number;
            /**
             * Format: int64
             * @description Sum of incomings of transactions (positive transaction amount values)
             */
            incomings: number;
        };
        TransactionTotalsResponse: {
            /** @description Collection of transaction totals per currency */
            data: components['schemas']['TransactionTotal'][];
        };
        TransactionsResponse: {
            /** @description Links */
            _links: components['schemas']['Links'];
            /** @description Transactions made within the filters provided for given balanceAccountId */
            data: components['schemas']['SingleTransaction'][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTransactions: {
        parameters: {
            query: {
                balanceAccountId: string;
                createdSince?: string;
                createdUntil?: string;
                categories?: string[];
                statuses?: components['schemas']['Status'][];
                currencies?: string[];
                minAmount?: number;
                maxAmount?: number;
                cursor?: string;
                sortDirection?: components['schemas']['SortDirection'];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TransactionsResponse'];
                };
            };
        };
    };
    downloadTransactions: {
        parameters: {
            query: {
                balanceAccountId: string;
                createdSince?: string;
                createdUntil?: string;
                categories?: string[];
                currencies?: string[];
                paymentPspReference?: string;
                columns: string[];
                sortDirection?: components['schemas']['SortDirection'];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'text/csv': components['schemas']['StreamingOutput'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DefaultErrorResponseEntity'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DefaultErrorResponseEntity'];
                };
            };
        };
    };
    getTransactionTotals: {
        parameters: {
            query: {
                balanceAccountId: string;
                createdSince?: string;
                createdUntil?: string;
                categories?: string[];
                statuses?: components['schemas']['Status'][];
                currencies?: string[];
                minAmount?: number;
                maxAmount?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TransactionTotalsResponse'];
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SingleTransaction'];
                };
            };
        };
    };
    initiateRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RefundRequest'];
            };
        };
        responses: {
            /** @description OK - the request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['RefundResponse'];
                };
            };
        };
    };
}
