name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  GITHUB_TOKEN:
    description: 'Github token used to checkout repo'
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'

    - name: Set up Git user
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install dependencies
      shell: bash
      run: |
        pnpm config set registry=https://registry.npmjs.org/
        pnpm install
      env:
        HUSKY: "0"