name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  GITHUB_TOKEN:
    description: 'Github token used to checkout repo'
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'

    - name: Set up Git user
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Prepare npmrc for CI
      shell: bash
      run: cp .npmrc.ci .npmrc

    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile --registry=https://registry.npmjs.org/ --config.resolution-mode=highest --verify-store-integrity=false
      env:
        HUSKY: "0"

    - name: Security Check - Validate Registry Sources
      shell: bash
      run: npx lockfile-lint --path pnpm-lock.yaml --type pnpm --validate-https --allowed-hosts registry.npmjs.org