import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { assertValidTranslationContract } from '../../packages/shared/core/src/translation-contract/validate';
import { parseV1TranslationTemplate } from '../../packages/shared/core/src/translation-contract/template';
import type {
    DomainTranslationSources,
    TranslationContractRegistry,
    TranslationSource,
} from '../../packages/shared/core/src/translation-contract/types';

export type TranslationContractArtifacts = Readonly<{
    catalogMarkdown: string;
    runtimeTypescript: string;
}>;

export const readJson = <Value>(path: string): Value => JSON.parse(readFileSync(path, 'utf8')) as Value;

export const getInstalledBentoTranslationKeys = (root: string): readonly string[] => {
    const requireFromReports = createRequire(resolve(root, 'packages/domains/reports/package.json'));
    const packageEntryPath = requireFromReports.resolve('@adyen/bento-vue3');
    const declarationPath = resolve(dirname(packageEntryPath), '@types/bento-translation-keys.generated.d.ts');
    const declaration = readFileSync(declarationPath, 'utf8');
    const marker = 'export type BentoTranslationKey =';
    const union = declaration.slice(declaration.indexOf(marker) + marker.length);
    const keys: string[] = [];

    for (const line of union.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed.startsWith('|')) continue;
        const firstQuote = trimmed.indexOf("'");
        const lastQuote = trimmed.lastIndexOf("'");
        if (firstQuote < 0 || lastQuote <= firstQuote) continue;
        keys.push(trimmed.slice(firstQuote + 1, lastQuote));
    }

    return keys.sort();
};

const getRoutedBentoKeys = (registry: TranslationContractRegistry): readonly string[] =>
    [...new Set(registry.routes.flatMap(({ targets }) => targets.filter(target => target.kind === 'bento').map(target => target.key)))].sort();

const getFallbackPlaceholderContracts = (
    registry: TranslationContractRegistry,
    domainSources: DomainTranslationSources,
    publicTemplates: TranslationSource
): Readonly<Record<string, readonly string[]>> =>
    Object.fromEntries(
        registry.routes.flatMap(route => {
            if (publicTemplates[route.publicKey] !== undefined) return [];

            const domainTemplate = route.targets
                .filter((target): target is Extract<(typeof route.targets)[number], { kind: 'domain' }> => target.kind === 'domain')
                .map(target => domainSources[target.domain]?.[target.key])
                .find((template): template is string => template !== undefined);
            const placeholders = domainTemplate === undefined ? route.placeholders : parseV1TranslationTemplate(domainTemplate).placeholders;

            return [[route.publicKey, placeholders ?? []]];
        })
    );

const toRuntimeSource = (
    registry: TranslationContractRegistry,
    bentoKeys: readonly string[],
    fallbackPlaceholderContracts: Readonly<Record<string, readonly string[]>>
): string => {
    const publicKeys = [...new Set(registry.routes.map(({ publicKey }) => publicKey))].sort();
    const routedBentoKeys = getRoutedBentoKeys(registry);

    return `/* This file is generated by scripts/translation-contract/generate.ts. Do not edit manually. */

export const V2_PUBLIC_TRANSLATION_KEYS = ${JSON.stringify(publicKeys, null, 4)} as const;
export const V2_PUBLIC_TRANSLATION_PLACEHOLDER_CONTRACTS = ${JSON.stringify(fallbackPlaceholderContracts, null, 4)} as const;
export const V2_BENTO_TRANSLATION_KEYS = ${JSON.stringify(bentoKeys, null, 4)} as const;
export const V2_ROUTED_BENTO_TRANSLATION_KEYS = ${JSON.stringify(routedBentoKeys, null, 4)} as const;
export const V2_TRANSLATION_ROUTES = ${JSON.stringify(registry.routes, null, 4)} as const;
export const V2_TRANSLATION_ALIASES = ${JSON.stringify(registry.aliases, null, 4)} as const;

export type V2PublicTranslationKey = (typeof V2_PUBLIC_TRANSLATION_KEYS)[number];
export type V2BentoTranslationKey = (typeof V2_BENTO_TRANSLATION_KEYS)[number];
`;
};

const toCatalogMarkdown = (registry: TranslationContractRegistry, bentoKeys: readonly string[]): string => {
    const rows = registry.routes
        .flatMap(route =>
            route.targets.map(target => {
                const targetName = target.kind === 'domain' ? `${target.domain}:${target.key}` : target.key;
                return `| \`${route.publicKey}\` | ${target.kind} | \`${targetName}\` | ${target.format} |`;
            })
        )
        .sort();
    const routedBentoKeys = getRoutedBentoKeys(registry);

    return `# Generated V2 translation catalog

> Generated by \`pnpm run translations:contract:generate\`. Do not edit manually.

- Public keys: ${new Set(registry.routes.map(({ publicKey }) => publicKey)).size}
- Route targets: ${registry.routes.reduce((count, { targets }) => count + targets.length, 0)}
- Installed Bento keys: ${bentoKeys.length}
- Routed Bento keys: ${routedBentoKeys.length}
- Intentionally unrouted Bento keys: ${bentoKeys.length - routedBentoKeys.length}

| Public key | Target kind | Target | Format |
| --- | --- | --- | --- |
${rows.join('\n')}
`;
};

export const buildTranslationContractArtifacts = (input: {
    bentoKeys: readonly string[];
    domainSources: DomainTranslationSources;
    publicTemplates: TranslationSource;
    registry: TranslationContractRegistry;
}): TranslationContractArtifacts => {
    assertValidTranslationContract({
        ...input,
        bentoKeys: new Set(input.bentoKeys),
    });

    return {
        catalogMarkdown: toCatalogMarkdown(input.registry, input.bentoKeys),
        runtimeTypescript: toRuntimeSource(
            input.registry,
            input.bentoKeys,
            getFallbackPlaceholderContracts(input.registry, input.domainSources, input.publicTemplates)
        ),
    };
};
