/**
 * Auto-generate IconName type declaration from icons directory.
 * Scans src/images/icons/*.svg and updates src/types/virtual-modules.d.ts
 *
 * Run: pnpm run types:generate:icons
 */

import { readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ICONS_DIR = resolve(process.cwd(), 'src/images/icons');
const TYPES_FILE = resolve(process.cwd(), 'src/types/virtual-modules.d.ts');

/**
 * Discover all icon files in the icons directory
 */
const discoverIcons = (): string[] => {
    try {
        const files = readdirSync(ICONS_DIR);
        return files
            .filter(file => file.endsWith('.svg'))
            .map(file => file.replace('.svg', ''))
            .sort();
    } catch (err) {
        console.error(`Error reading icons directory: ${ICONS_DIR}`);
        throw err;
    }
};

/**
 * Generate the IconName type union
 */
const generateIconNameType = (iconNames: string[]): string => {
    return iconNames.map(name => `        | '${name}'`).join('\n');
};

/**
 * Generate the complete virtual-modules.d.ts content
 */
const generateTypesFile = (iconNames: string[]): string => {
    const iconNameType = generateIconNameType(iconNames);

    return `/**
 * Type declarations for virtual:tree-shaken-icons module.
 * 
 * The virtual module is generated at build time and tree-shakes to only
 * include icons actually used in the code. TypeScript sees all possible
 * icon names for autocomplete, while the runtime bundle only includes what's used.
 * 
 * This file is auto-generated by scripts/generate-icon-types.ts
 * Run: pnpm run types:generate:icons
 */

declare module 'virtual:tree-shaken-icons' {
    /**
     * Union type of all available icon names.
     * Auto-discovered from src/images/icons/*.svg
     * 
     * Total icons: ${iconNames.length}
     */
    export type IconName =
${iconNameType};

    /**
     * Icon registry mapping icon names to their dynamic import functions.
     * Tree-shaken at build time to only include icons actually used in the code.
     */
    export const icons: Record<IconName, () => Promise<{ default: any }>>;
}
`;
};

/**
 * Main execution
 */
const main = () => {
    console.log('🔍 Scanning icons directory...');
    const iconNames = discoverIcons();

    console.log(`✓ Found ${iconNames.length} icon(s): ${iconNames.join(', ')}`);

    console.log('📝 Generating type declarations...');
    const content = generateTypesFile(iconNames);

    console.log(`💾 Writing to ${TYPES_FILE}...`);
    writeFileSync(TYPES_FILE, content, 'utf-8');

    console.log('✅ Icon types generated successfully!');
};

main();
