#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_BLUE='\033[1;34m'
NC='\033[0m'

echo "----- ${LIGHT_BLUE}Pre-commit hook checks started${NC} -----"

echo "${LIGHT_GREEN}Formatting code with prettier!${NC}"
npx lint-staged --allow-empty

# Sucessfull checking
echo " ${GREEN}✓✓✓✓✓ prettier code format checked${NC}"
