name: Publish npm logs

description: Publish npm logs as build artifacts
runs:
  using: composite
  steps:
    - name: Archive npm failure logs
      uses: actions/upload-artifact@v4
      with:
        name: npm-logs
        path: ~/.npm/_logs