name: Publish pnpm logs

description: Publish pnpm logs as build artifacts
runs:
  using: composite
  steps:
    - name: Archive pnpm failure logs
      uses: actions/upload-artifact@v4
      with:
        name: pnpm-logs
        path: ~/.pnpm/_logs