name: Daily Contract Tests

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  contract-tests:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [contract-live, contract-test]
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Run contract tests
        run: npm run test:contract
        env:
          SESSION_ACCOUNT_HOLDER: ${{ secrets.SESSION_ACCOUNT_HOLDER }}
          SESSION_API_URL: ${{ secrets.SESSION_API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          BALANCE_ACCOUNT: ${{ secrets.BALANCE_ACCOUNT }}
          NODE_ENV: ${{ matrix.environment == 'contract-live' && 'live' || 'test' }}
          CI: true

  notify:
    needs: contract-tests
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ "${{ needs.contract-tests.result }}" == "success" ]]; then
            STATUS="✅ Contract tests succeeded"
          else
            STATUS="@here Contract tests failed ❌❌"
          fi
          curl -X POST -H 'Content-Type: application/json' --data "{\"text\":\"$STATUS\n\nWorkflow: ${{ github.workflow }}\n\nSee <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|details>\"}" $SLACK_WEBHOOK_URL