name: Download translations

on:
  workflow_dispatch:

jobs:
  download-files:
    name: Download completed translation files
    runs-on: ubuntu-latest
    environment: smartling-translations # provides Smartling credentials
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Run setup steps for translation tasks
        uses: ./.github/actions/setup-smartling
        with:
          npm_token: ${{ secrets.NPM_SMARTLING_BOT_READ_TOKEN }}
          project_id: ${{ secrets.SMARTLING_PROJECT_ID }}
          user_identifier: ${{ secrets.SMARTLING_USER_IDENTIFIER }}
          user_secret: ${{ secrets.SMARTLING_USER_SECRET }}

      - name: Download and commit files
        run: |
          # Checkout the default branch
          gh pr checkout $BASE_BRANCH -b $NEW_BRANCH

          # Download files from Smartling
          npx -y @adyen/smartling-bot@0.6.x download-files

          # Stage downloaded files
          for source_path in $(jq -r '.translationSourcePaths[]' .i18nrc); do
            root_path=$(dirname $source_path)
            for locale in $(jq -r '.locales[]' .i18nrc); do
              echo $(realpath "./$root_path/$locale.json")
              git add $(realpath "./$root_path/$locale.json")
            done
          done

          if git diff-index --cached --quiet HEAD; then
            # there are no changes to commit
            echo "No translations updates"
          else
            # Create a commit for staged files and push
            git commit -m $COMMIT_TITLE
            git push

            # Create a PR on the default branch
            gh pr create --base $BASE_BRANCH --head $NEW_BRANCH --fill
          fi
        env:
          BASE_BRANCH: "develop"
          NEW_BRANCH: "bot/translations"
          COMMIT_TITLE: "Update translations"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
