name: Download translations

on:
  workflow_dispatch:

jobs:
  download-files:
    name: Download completed translation files
    if: github.event_name == 'workflow_dispatch' && (github.ref_name == 'develop' || startsWith(github.ref_name, 'group/'))
    runs-on: ubuntu-latest
    environment: smartling-translations # provides Smartling credentials
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Run setup steps for translation tasks
        uses: ./.github/actions/setup-smartling
        with:
          npm_token: ${{ secrets.NPM_SMARTLING_BOT_READ_TOKEN }}
          project_id: ${{ secrets.SMARTLING_PROJECT_ID }}
          user_identifier: ${{ secrets.SMARTLING_USER_IDENTIFIER }}
          user_secret: ${{ secrets.SMARTLING_USER_SECRET }}

      - name: Download and commit files
        run: |
          # Checkout new branch from the default branch
          git checkout -B ${{ env.BRANCH_NAME }} ${{ env.BASE_REF }}

          # Download files from Smartling
          npx -y @adyen/smartling-bot@0.x.x download-files -p ./scripts/process-translations/commit-translations.sh
        env:
          BASE_REF: ${{ github.ref_name }}
          BRANCH_NAME: "bot/translations"
          COMMIT_TITLE: "Update translations"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
