name: End-to-End Tests

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  e2e-local-mocked-api:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
      PLAYGROUND_HOST: localhost
      PLAYGROUND_PORT: 4173
      VITE_API_URL: http://localhost:4173
      MOCK_SERVER_PORT: 8083
      VITE_MODE: demo
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Fetch latest Chrome stable version
        id: latest-chrome-version
        run: echo "version=$( curl -s https://omahaproxy.appspot.com/linux )" >> $GITHUB_OUTPUT

      - name: Cache Chrome
        id: cache-chrome
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/chromium/latest
          key: chrome-${{ steps.latest-chrome-version.outputs.version }}

      - name: Install Chrome (if not available in cache)
        if: steps.cache-chrome.outputs.cache-hit != 'true'
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Build demo
        run: npm run build:demo

      - name: Run tests
        run: npm run test:e2e -- --project local-chrome

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ github.sha }}
          path: playwright-report/
          retention-days: 3