name: NPM publish package

on:
  workflow_dispatch:
    inputs:
      dry-run-publish:
        description: 'Dry-run the write steps (do not actually commit or publish to NPM)'
        type: boolean
        default: false
  workflow_call:
    inputs:
      called-from-other-workflow:
        description: 'Used as a way to distinguish workflow_call from workflow_dispatch'
        type: boolean
        required: false
        default: true
      source_run_id:
        description: 'Run ID that produced the build artifact'
        required: true
        type: string

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment: publish-package  # contains NPM_PLATFORM_EXPERIENCE_TOKEN
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Determine the release version
        run: |
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create a temporary directory for artifacts
        run: mkdir -p ${{ runner.temp }}/artifacts/

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: adyen-adyen-platform-experience-web-${{ env.PACKAGE_VERSION }}
          run-id: ${{ inputs.source_run_id }}
          path: ${{ runner.temp }}/artifact
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract archive in $RUNNER_TEMP
        working-directory: ${{ runner.temp }}/artifact
        run: |
          tar -xzf adyen-adyen-platform-experience-web-${{ env.PACKAGE_VERSION }}.tgz \
              --strip-components=1 package

      - name: Copy dist/ to workspace
        run: |
          cp -R ${{ runner.temp }}/artifact/dist ./dist

      - name: Publish to the NPM registry (dry run)
        if: github.event.inputs.dry-run-publish == 'true'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PLATFORM_EXPERIENCE_TOKEN }}
          npm publish --dry-run

      - name: Publish to the NPM registry
        if: github.event.inputs.dry-run-publish != 'true'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PLATFORM_EXPERIENCE_TOKEN }}
          npm publish

      - name: Archive npm failure logs
        uses: ./.github/actions/publish-npm-logs
        if: failure()
