name: NPM publish package

on:
  workflow_call:
    inputs:
      called-from-other-workflow:
        description: 'Used as a way to distinguish workflow_call from workflow_dispatch'
        type: boolean
        required: false
        default: true
      source_run_id:
        description: 'Run ID that produced the build artifact'
        required: true
        type: string
      npm_tag:
        description: 'npm dist-tag to publish under (latest, beta, alpha, rc, next)'
        required: false
        type: string
        default: 'latest'

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env
        with:
          NPM_READ_ONLY_TOKEN: ${{ secrets.NPM_READ_ONLY_TOKEN }}

      - name: Determine the release version
        run: |
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "PACKAGE_TARBALL=${RUNNER_TEMP}/artifact/adyen-adyen-platform-experience-web-${PACKAGE_VERSION}.tgz" >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: adyen-adyen-platform-experience-web-${{ env.PACKAGE_VERSION }}
          run-id: ${{ inputs.source_run_id }}
          path: ${{ runner.temp }}/artifact
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to the NPM registry (dry run)
        if: github.event.inputs.dry-run-publish == 'true'
        run: |
          npm publish "${{ env.PACKAGE_TARBALL }}" --dry-run

      - name: Publish to the NPM registry
        if: github.event.inputs.dry-run-publish != 'true'
        run: |
          npm publish "${{ env.PACKAGE_TARBALL }}" --tag=${{ inputs.npm_tag }}

      - name: Archive npm failure logs
        uses: ./.github/actions/publish-npm-logs
        if: failure()
