name: NPM publish package

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      dry-run-publish:
        description: 'Dry-run the write steps (do not actually commit or publish to NPM)'
        type: boolean
        default: false

  # we can't use the release:created trigger because it doesn't trigger on releases created by github-actions bot
  # so instead, this has to be directly called by `tag-and-release.yml`
  workflow_call:
    inputs:
      called-from-other-workflow:
        description: 'Used as a way to distinguish workflow_call from workflow_dispatch'
        type: boolean
        required: false
        default: true

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment: publish-package  # contains NPM_PLATFORM_EXPERIENCE_TOKEN
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Determine the release version
        run: |
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Download build artifacts (from previous workflow)
        run: |
          gh run download -n adyen-adyen-platform-experience-web-${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Expand build artifacts archive to get `./dist`
        run: |
          tar -xzf adyen-adyen-platform-experience-web-${{ env.PACKAGE_VERSION }}.tgz --strip-components=1 package

      - name: Check that `dist` directory is present and not empty
        run: |
          [ -d ./dist ] && [ ! -z "$(ls -A ./dist)" ]

      - name: Publish to the NPM registry (dry run)
        if: github.event.inputs.dry-run-publish == 'true'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PLATFORM_EXPERIENCE_TOKEN }}
          npm publish --dry-run

      - name: Publish to the NPM registry
        if: github.event.inputs.dry-run-publish != 'true'
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PLATFORM_EXPERIENCE_TOKEN }}
          npm publish

      - name: Archive npm failure logs
        uses: ./.github/actions/publish-npm-logs
        if: failure()