name: Pull Request workflow

on:
  pull_request:
    branches:
      - main
      - develop
      - group/*
      - bot/translations
    types: [opened, synchronize, reopened]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env
        with:
          NPM_READ_ONLY_TOKEN: ${{ secrets.NPM_READ_ONLY_TOKEN }}

      - name: Run unit tests
        run: pnpm run test

      - name: Build library
        run: pnpm run build