name: Close Stale Issues and Pull Requests

on:
  schedule:
    - cron: '0 8 * * 1'  # Runs at 8 AM UTC every Monday

permissions:
  issues: write
  pull-requests: write

jobs:
  close_stale_issues_and_prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close stale issues and pull requests
        uses: actions/stale@v9
        with:
          stale-issue-message: |
            This issue has been marked as stale because it has been inactive for more than 30 days.
            Please update this issue or it will be automatically closed in 7 days.
          close-issue-message: |
            This issue has been automatically closed because it has been inactive for more than 37 days.
            Please reopen if you still need assistance.
          stale-pr-message: |
            This pull request has been marked as stale because it has been inactive for more than 14 days.
            Please update this pull request or it will be automatically closed in 7 days.
          close-pr-message: |
            This pull request has been automatically closed because it has been inactive for more than 21 days.
            Please reopen if you still intend to submit this pull request.
          days-before-stale-issue: 30
          days-before-close-issue: 7
          days-before-stale-pr: 14
          days-before-close-pr: 7
          stale-issue-label: stale
          stale-pr-label: stale
          close-issue-label: 'closed-stale'
          close-pr-label: 'closed-stale'
          exempt-issue-labels: 'pinned'
          exempt-pr-labels: 'work-in-progress'
          remove-stale-when-updated: true
