name: Pull Request workflow

on:
  pull_request:
    branches:
      - main # or the name of your default branch
    types: [opened, synchronize, reopened]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  is-pr-approved:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - id: check-approval
        run: gh pr status --json reviews -q '.currentBranch.reviews' | jq '.[]' | jq '.state' | grep APPROVED
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true

      - run: echo ${{ steps.check-approval.outcome == 'success' }}
    outputs:
      approved: ${{ steps.check-approval.outcome == 'success' }}
  generate-schemas:
    needs: is-pr-approved
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      REPO_URL: ${{ secrets.REPO_URL }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      ENV: "CI"
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Create variables
        run: npm run schemas:variables "${{ env.REPO_URL }}" "${{ env.REPO_TOKEN }}" "${{ env.PROJECT_ID }}"

      - name: Generate schemas
        run: npm run schemas:generate

      - name: Build library
        run: npm run build