name: Upload translations

on:
  workflow_dispatch:
    inputs:
      authorize_job:
        description: 'Automatically authorize job'
        type: boolean
        default: false

jobs:
  upload-files:
    name: Upload translation source files
    if: github.event_name == 'workflow_dispatch' && github.ref_name == 'develop'
    runs-on: ubuntu-latest
    environment: smartling-translations # provides Smartling credentials
    permissions:
      actions: write
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env
        with:
          NPM_READ_ONLY_TOKEN: ${{ secrets.NPM_READ_ONLY_TOKEN }}

      - name: Run setup steps for translation tasks
        id: setup-smartling
        uses: ./.github/actions/setup-smartling
        with:
          npm_token: ${{ secrets.NPM_READ_ONLY_TOKEN }}
          project_id: ${{ secrets.SMARTLING_PROJECT_ID }}
          user_identifier: ${{ secrets.SMARTLING_USER_IDENTIFIER }}
          user_secret: ${{ secrets.SMARTLING_USER_SECRET }}

      - name: Create translations job (with authorization)
        if: ${{ inputs.authorize_job }}
        run: '"$SMARTLING_BOT_CLI" upload-files -ar "$REF_NAME"'
        env:
          REF_NAME: ${{ github.ref_name }}
          SMARTLING_BOT_CLI: ${{ steps.setup-smartling.outputs.smartling_bot_cli }}

      - name: Create translations job (without authorization)
        if: ${{ ! inputs.authorize_job }}
        run: '"$SMARTLING_BOT_CLI" upload-files -r "$REF_NAME"'
        env:
          REF_NAME: ${{ github.ref_name }}
          SMARTLING_BOT_CLI: ${{ steps.setup-smartling.outputs.smartling_bot_cli }}
