name: Upload translations

on:
  workflow_dispatch:
    inputs:
      authorize_job:
        description: 'TRUE to automatically authorize the translations job'
        required: false
        type: boolean
        default: FALSE

jobs:
  upload-files:
    name: Download translation source files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Run setup steps for translation tasks
        uses: ./.github/actions/setup-smartling

      - name: Create translations job (with authorization)
        if: ${{ inputs.authorize_job }}
        run: npx @adyen/smartling-bot@0.3.1 upload-files --auto-authorization

      - name: Create translations job (without authorization)
        if: ${{ ! inputs.authorize_job }}
        run: npx @adyen/smartling-bot@0.3.1 upload-files
