name: Upload translations

on:
  workflow_dispatch:
    inputs:
      authorize_job:
        description: 'TRUE to automatically authorize the translations job'
        required: false
        type: boolean
        default: FALSE

jobs:
  initialize:
    name: Initialization steps
    runs-on: ubuntu-latest
    environment: smartling-translations # provides Smartling credentials
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Run setup steps for translation tasks
        uses: ./.github/actions/setup-smartling
        with:
          project_id: ${{ secrets.SMARTLING_PROJECT_ID }}
          user_identifier: ${{ secrets.SMARTLING_USER_IDENTIFIER }}
          user_secret: ${{ secrets.SMARTLING_USER_SECRET }}

  upload-files:
    needs: initialize
    name: Upload translation source files
    runs-on: ubuntu-latest
    environment: publish-package # provides NPM credentials
    steps:
      - name: Create translations job (with authorization)
        if: ${{ inputs.authorize_job }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npx @adyen/smartling-bot@0.3.1 upload-files --auto-authorization

      - name: Create translations job (without authorization)
        if: ${{ ! inputs.authorize_job }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npx @adyen/smartling-bot@0.3.1 upload-files
