name: Version Bump

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  version-bump:
    if: |
      github.repository == 'adyen/adyen-platform-experience-web' &&
      (github.event_name == 'workflow_dispatch' ||
       (github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.title, 'Start release v')))
    name: Version bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Run the preliminary setup steps
        uses: ./.github/actions/setup-env

      - name: Determine new version
        run: |
          pnpm changeset version
          NEW_VERSION=$(jq -r '.version' package.json)
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
          git checkout -- .

      - name: Create Version Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "Bump v${{ env.NEW_VERSION }}"
          title: "Bump package version v${{ env.NEW_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
